version: '3.8'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2019-latest
    user: root
    environment:
      SA_PASSWORD: "Senha1234!"
      ACCEPT_EULA: "Y"
      MSSQL_TCP_ENABLED: 1
      MSSQL_SA_ACCEPT_REMOTE_CONNECTIONS: 1
    ports:
      - "1433:1433"

  dotnet:
    build:
      context: .
      dockerfile: ./Backend/LeadApplication/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    ports:
      - "5000:5000"
    depends_on:
      - sqlserver

  react:
    build:
      context: .
      dockerfile: ./Frontend/Dockerfile
 
    ports:
      - "3000:3000"
      - "3010:3010"
    depends_on:
      - dotnet
